# Generated by Django 4.2.1 on 2024-05-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('existencia', models.IntegerField()),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
    ]
