# Generated by Django 4.2.1 on 2024-05-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_producto_imagen_producto_imagen_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen_url',
            new_name='imagen',
        ),
    ]
